global using Shared.DDD;
global using Shared.Data.Seed;
global using Shared.Data;
global using Catalog.Products.Models;
global using Catalog.Products.Events;
global using Catalog.Data.Seed;
global using Catalog.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;